name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-24.04
          - windows-2022
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          # Match goreleaser's Go version
          go-version: 1.23
          cache-dependency-path: |
            **/go.sum
            build/versions.go

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build -v lint

      - name: run tests
        run: go run ./build -v test

      - run: go run ./build snapshot
        if: startsWith(matrix.os, 'ubuntu-')
