name: Go Dependabot PR Workspace Sync

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sync:
    uses: curioswitch/go-build/.github/workflows/export-dependabot-go-sync.yaml@66ac0828fa9172346ee4a766f66c088b55f057fc
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
