name: Go Dependabot PR Workspace Sync

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sync:
    uses: curioswitch/go-build/.github/workflows/export-dependabot-go-sync.yaml@b4bb86391b1e39db0dd8cad98e4d8be49c298077
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
