name: Go Dependabot PR Workspace Sync

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sync:
    uses: curioswitch/go-build/.github/workflows/export-dependabot-go-sync.yaml@e593998ac22b4de0e3e82d60d6b03d17fef1178f
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
